#!/usr/bin/env python3
"""Reference model for ring stepping, written from 05_avr_design.md.

The card holds a 128-bit ring and a phase counter. On each REQ rising edge it
reports the ring bit at the current phase (1 releases VOTE, 0 drives VOTE low),
then advances the phase, wrapping at the modulus rather than at 128.

Running this file rewrites vectors_sieve.txt. The host test reads that file, so
`make test` never needs Python.
"""

import pathlib

RING_BYTES = 16
MODULI = [2, 3, 7, 30, 127, 128]
STEPS = 400


def ring_bit(ring, phase):
    """Bit `phase` of the ring: bit (phase % 8) of byte (phase // 8), LSB first."""
    return (ring[phase // 8] >> (phase % 8)) & 1


def step_case(modulus, ring, arm_phase, steps):
    """Decisions for `steps` REQ edges, starting armed at `arm_phase`."""
    out = []
    phase = arm_phase
    for _ in range(steps):
        out.append(ring_bit(ring, phase))
        phase = (phase + 1) % modulus
    return out


def set_bits(indices):
    ring = bytearray(RING_BYTES)
    for i in indices:
        ring[i // 8] |= 1 << (i % 8)
    return bytes(ring)


def lcg_ring(seed):
    """Deterministic pseudo-random ring, so vectors do not depend on Python."""
    x = seed
    out = bytearray()
    for _ in range(RING_BYTES):
        x = (x * 1103515245 + 12345) & 0x7FFFFFFF
        out.append((x >> 16) & 0xFF)
    return bytes(out)


def cases():
    for modulus in MODULI:
        rings = [
            ("all clear", bytes(RING_BYTES)),
            ("all set", b"\xff" * RING_BYTES),
            ("only phase 0", set_bits([0])),
            ("only phase modulus-1", set_bits([modulus - 1])),
            ("pseudo-random", lcg_ring(modulus)),
        ]
        for index, (_, ring) in enumerate(rings):
            arm_phase = (index * 3) % modulus
            yield modulus, ring, arm_phase


def main():
    path = pathlib.Path(__file__).with_name("vectors_sieve.txt")
    lines = [
        "# Generated by model.py. Do not edit.",
        "# case <modulus> <16 ring bytes, hex, byte 0 first> <arm phase> <steps>",
        "# then one line of that many decisions, 1 release VOTE, 0 drive VOTE low.",
    ]
    for modulus, ring, arm_phase in cases():
        lines.append(f"case {modulus} {ring.hex()} {arm_phase} {STEPS}")
        lines.append("".join(str(b) for b in step_case(modulus, ring, arm_phase, STEPS)))
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
